[package]
name = "rust_lib_devtools"
version = "0.1.0"
edition = "2021"
rust-version="1.86.0"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
flutter_rust_bridge = "=2.7.0"
serde_json = "1.0"
json5 = "0.4.1"
json-repair = "0.4.0"
